// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteRefreshToken(ctx context.Context, id uuid.UUID) error
	DeleteURL(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAllActiveUsers(ctx context.Context) ([]User, error)
	GetAllURLs(ctx context.Context) ([]Url, error)
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	GetRefreshTokenByToken(ctx context.Context, token string) (RefreshToken, error)
	GetRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error)
	GetURLByID(ctx context.Context, id uuid.UUID) (Url, error)
	GetURLByShortURL(ctx context.Context, shortUrl string) (Url, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementURLCount(ctx context.Context, id uuid.UUID) (Url, error)
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	ValidateRefreshToken(ctx context.Context, token string) (RefreshToken, error)
}

var _ Querier = (*Queries)(nil)
