// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url_users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createURLUser = `-- name: CreateURLUser :one
INSERT INTO url_users (url_id, user_id)
VALUES ($1, $2)
RETURNING id, url_id, user_id, created_at, updated_at
`

type CreateURLUserParams struct {
	UrlID  uuid.UUID `json:"url_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateURLUser(ctx context.Context, arg CreateURLUserParams) (UrlUser, error) {
	row := q.db.QueryRowContext(ctx, createURLUser, arg.UrlID, arg.UserID)
	var i UrlUser
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getURLsByUserID = `-- name: GetURLsByUserID :many
SELECT u.id, u.url_code, u.original_url, u.click_count, u.created_at, u.updated_at
FROM urls u
JOIN url_users uu ON uu.url_id = u.id
WHERE uu.user_id = $1
ORDER BY u.created_at DESC
`

func (q *Queries) GetURLsByUserID(ctx context.Context, userID uuid.UUID) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getURLsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UrlCode,
			&i.OriginalUrl,
			&i.ClickCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
