// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (url_code, original_url, click_count)
VALUES ($1, $2, $3)
RETURNING id, url_code, original_url, click_count, created_at, updated_at
`

type CreateURLParams struct {
	UrlCode     string        `json:"url_code"`
	OriginalUrl string        `json:"original_url"`
	ClickCount  sql.NullInt32 `json:"click_count"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL, arg.UrlCode, arg.OriginalUrl, arg.ClickCount)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UrlCode,
		&i.OriginalUrl,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls
WHERE id = $1
`

func (q *Queries) DeleteURL(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteURL, id)
	return err
}

const getAllURLs = `-- name: GetAllURLs :many
SELECT id, url_code, original_url, click_count, created_at, updated_at
FROM urls
ORDER BY created_at DESC
`

func (q *Queries) GetAllURLs(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getAllURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.UrlCode,
			&i.OriginalUrl,
			&i.ClickCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLByID = `-- name: GetURLByID :one
SELECT id, url_code, original_url, click_count, created_at, updated_at
FROM urls
WHERE id = $1
`

func (q *Queries) GetURLByID(ctx context.Context, id uuid.UUID) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByID, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UrlCode,
		&i.OriginalUrl,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getURLByURLCode = `-- name: GetURLByURLCode :one
SELECT id, url_code, original_url, click_count, created_at, updated_at
FROM urls
WHERE url_code = $1
`

func (q *Queries) GetURLByURLCode(ctx context.Context, urlCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByURLCode, urlCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UrlCode,
		&i.OriginalUrl,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementURLCount = `-- name: IncrementURLCount :one
UPDATE urls
SET click_count = click_count + 1, updated_at = NOW()
WHERE id = $1
RETURNING id, url_code, original_url, click_count, created_at, updated_at
`

func (q *Queries) IncrementURLCount(ctx context.Context, id uuid.UUID) (Url, error) {
	row := q.db.QueryRowContext(ctx, incrementURLCount, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UrlCode,
		&i.OriginalUrl,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls
SET url_code = $2, original_url = $3, click_count = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, url_code, original_url, click_count, created_at, updated_at
`

type UpdateURLParams struct {
	ID          uuid.UUID     `json:"id"`
	UrlCode     string        `json:"url_code"`
	OriginalUrl string        `json:"original_url"`
	ClickCount  sql.NullInt32 `json:"click_count"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateURL,
		arg.ID,
		arg.UrlCode,
		arg.OriginalUrl,
		arg.ClickCount,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.UrlCode,
		&i.OriginalUrl,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
