// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (short_url, original_url, count_code)
VALUES ($1, $2, $3)
RETURNING id, short_url, original_url, count_code, created_at, updated_at
`

type CreateURLParams struct {
	ShortUrl    string        `json:"short_url"`
	OriginalUrl string        `json:"original_url"`
	CountCode   sql.NullInt32 `json:"count_code"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createURL, arg.ShortUrl, arg.OriginalUrl, arg.CountCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.CountCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls
WHERE id = $1
`

func (q *Queries) DeleteURL(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteURL, id)
	return err
}

const getAllURLs = `-- name: GetAllURLs :many
SELECT id, short_url, original_url, count_code, created_at, updated_at
FROM urls
ORDER BY created_at DESC
`

func (q *Queries) GetAllURLs(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getAllURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.OriginalUrl,
			&i.CountCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLByID = `-- name: GetURLByID :one
SELECT id, short_url, original_url, count_code, created_at, updated_at
FROM urls
WHERE id = $1
`

func (q *Queries) GetURLByID(ctx context.Context, id uuid.UUID) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByID, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.CountCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getURLByShortURL = `-- name: GetURLByShortURL :one
SELECT id, short_url, original_url, count_code, created_at, updated_at
FROM urls
WHERE short_url = $1
`

func (q *Queries) GetURLByShortURL(ctx context.Context, shortUrl string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getURLByShortURL, shortUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.CountCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementURLCount = `-- name: IncrementURLCount :one
UPDATE urls
SET count_code = count_code + 1, updated_at = NOW()
WHERE id = $1
RETURNING id, short_url, original_url, count_code, created_at, updated_at
`

func (q *Queries) IncrementURLCount(ctx context.Context, id uuid.UUID) (Url, error) {
	row := q.db.QueryRowContext(ctx, incrementURLCount, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.CountCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls
SET short_url = $2, original_url = $3, count_code = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, short_url, original_url, count_code, created_at, updated_at
`

type UpdateURLParams struct {
	ID          uuid.UUID     `json:"id"`
	ShortUrl    string        `json:"short_url"`
	OriginalUrl string        `json:"original_url"`
	CountCode   sql.NullInt32 `json:"count_code"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, updateURL,
		arg.ID,
		arg.ShortUrl,
		arg.OriginalUrl,
		arg.CountCode,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.OriginalUrl,
		&i.CountCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
